version: "3.6"
services:
  fake-passport-bupt:
    build: .
    image: charlie0129/fake-passport-bupt
    container_name: fake-passport-bupt
    restart: unless-stopped
    networks:
      - traefik-global-proxy # change this to you network where traefik lives in
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fake-passport-bupt.rule=Host(`${WEBSITE_URL}`)"
      - "traefik.http.routers.fake-passport-bupt.entrypoints=web"
      - "traefik.http.services.fake-passport-bupt.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.fake-passport-bupt.middlewares=fake-passport-bupt-compress"
      - "traefik.http.middlewares.fake-passport-bupt-compress.compress=true"
    environment:
      - "NODE_ENV=production"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./config:/usr/src/app/config
    expose:
      - "${PORT}"

networks:
  traefik-global-proxy: # change this to you network where traefik lives in
    external: true
