version: "3.6"
services:
  fake-passport-bupt:
    build: .
    image: charlie0129/fake-passport-bupt
    container_name: fake-passport-bupt
    ports:
      - "${PORT}:${PORT}"
    environment:
      - "NODE_ENV=production"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./config:/usr/src/app/config
    expose:
      - "${PORT}"
